name: nwc
description: A dart package that simplifies the integration of Nostr Wallet Connect into client applications.
version: 1.0.0
repository: https://github.com/bringinxyz/nwc
homepage: https://github.com/bringinxyz/nwc
license: MIT

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  bip340: ^0.3.0
  convert: ^3.1.1
  crypto: ^3.0.2
  equatable: ^2.0.5
  hex: ^0.2.0
  bech32: ^0.2.2
  meta: ^1.8.0
  web_socket_channel: ^2.4.0
  pointycastle: ^3.9.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
